server:
  port: 7070


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my-pet
    username: ksubin
    password: 1396
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true